import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { viteSingleFile } from "vite-plugin-singlefile";

const fontsOffline = fileURLToPath(
  new URL("./src/styles/fonts.offline.css", import.meta.url),
);

// In offline mode, redirect the CDN-backed fonts.css import to the
// self-hosted fonts.offline.css (generated by scripts/build-offline-fonts.mjs)
// so the bundle has zero Google Fonts network dependency.
function offlineFonts(): Plugin {
  return {
    name: "offline-fonts",
    enforce: "pre",
    resolveId(id) {
      if (id.endsWith("styles/fonts.css")) return fontsOffline;
      return null;
    },
  };
}

export default defineConfig(({ mode }) => {
  const offline = mode === "offline";
  return {
    // Relative base so the single HTML opens straight from file:// (offline);
    // GitHub Pages path otherwise.
    base: offline ? "./" : mode === "production" ? "/brain-tumor-asno/" : "/",
    plugins: [
      react(),
      ...(offline ? [offlineFonts(), viteSingleFile()] : []),
    ],
    server: {
      port: 5175,
      fs: { allow: [".."] },
    },
  };
});
